language: python
python:
  - "3.8"

services:
  - mysql

install:
  - pip install -r requirements.txt
  
before_script:
  - ls -R tests
  - mysql -e 'CREATE DATABASE test_db;'
  
script:
  - source ~/virtualenv/python3.8/bin/activate
  - pytest tests/

env:
  global:
    - FLASK_ENV=testing
    - DATABASE_URL=mysql://admin:password@database-1.cza7wufaq8ub.us-east-1.rds.amazonaws.com:3306/fit_this
    - SQLALCHEMY_TRACK_MODIFICATIONS=False
    - MYSQL_DATABASE_URI=mysql://admin:password@database-1.cza7wufaq8ub.us-east-1.rds.amazonaws.com:3306/fit_this

notifications:
  email: false
