language: python
python:
  - "3.8"

services:
  - mysql

install:
  - pip install -r requirements.txt

before_script:
  - ls -R tests
  - mysql -e 'CREATE DATABASE test_db;'

script:
  - source ~/virtualenv/python3.8/bin/activate
  - export FLASK_ENV=testing
  - export DATABASE_URL=mysql://travis@localhost/test_db
  - export SECRET_KEY=your_secret_key  # Set your secret key here
  - export SQLALCHEMY_TRACK_MODIFICATIONS=True  # Set your SQLAlchemy track modifications configuration here

  - pytest tests/

env:
  global:
    - DATABASE_URL=mysql://travis@localhost/test_db
    - SQLALCHEMY_TRACK_MODIFICATIONS=True

notifications:
  email: false
