services:
  db:
    image: mysql:8
    command: '--default-authentication-plugin=caching_sha2_password'
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -u root --password=\"$$(cat /run/secrets/db-password)\" ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=fit_this
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
      - 33060

  backend:
    build:
      context: .
    restart: always
    env_file:
        - .env
    secrets:
      - db-password
    ports:
      - 5000:5000
    networks:
      - backnet
      - frontnet
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  backnet:
  frontnet: