"""empty message

Revision ID: 141fc801a14c
Revises: 4d25a38228d5
Create Date: 2023-12-06 02:45:49.192059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141fc801a14c'
down_revision = '4d25a38228d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_column('sequence')

    # ### end Alembic commands ###
