"""empty message

Revision ID: 307ba572a641
Revises: 
Create Date: 2023-12-19 17:02:54.438552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '307ba572a641'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_stats', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('last_modified', sa.Date(), nullable=False))
        batch_op.drop_column('energy_level')
        batch_op.drop_column('workout_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('energy_level', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('last_modified')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('workout_stats', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
