"""empty message

Revision ID: 41e2ce3ceacc
Revises: 
Create Date: 2023-12-02 16:05:09.875131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41e2ce3ceacc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_survey')
    with op.batch_alter_table('coach_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach_info', schema=None) as batch_op:
        batch_op.drop_column('approved')

    op.create_table('user_survey',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=False),
    sa.Column('energy_level', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mood_level', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hydration_level', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('calories_intake', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], name='user_survey_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
