"""empty message

Revision ID: 4d25a38228d5
Revises: d0211748bdbc
Create Date: 2023-12-06 02:34:07.247687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d25a38228d5'
down_revision = 'd0211748bdbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('last_modified', sa.Date(), nullable=False))
        batch_op.drop_column('workout_date')
        batch_op.drop_column('energy_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('energy_level', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('workout_date', sa.DATE(), nullable=False))
        batch_op.drop_column('last_modified')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
