"""empty message

Revision ID: 6cc079c4da96
Revises: f3f9a1e3b169
Create Date: 2023-11-29 16:12:06.421270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc079c4da96'
down_revision = 'f3f9a1e3b169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_goals', schema=None) as batch_op:
        batch_op.drop_constraint('member_goals_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'members', ['member_id'], ['member_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_goals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('member_goals_ibfk_1', 'members', ['member_id'], ['member_id'])

    # ### end Alembic commands ###
