"""empty message

Revision ID: 762797004345
Revises: 
Create Date: 2023-12-16 19:26:45.712360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '762797004345'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chathistory')
    with op.batch_alter_table('coaches_members_link', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches_members_link', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    op.create_table('chathistory',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('link_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chatkey', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('recorded_at', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['coaches_members_link.link_id'], name='chathistory_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
