"""empty message

Revision ID: 78c214ac14a9
Revises: 
Create Date: 2023-11-30 15:52:39.696216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78c214ac14a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))

    with op.batch_alter_table('personal_info', schema=None) as batch_op:
        batch_op.drop_index('username')

    with op.batch_alter_table('workout_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.drop_column('recorded_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.drop_column('date')

    with op.batch_alter_table('personal_info', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=False)

    with op.batch_alter_table('coach_info', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
