"""empty message

Revision ID: 93797319715e
Revises: 
Create Date: 2023-11-30 01:57:10.578523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93797319715e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.drop_column('recorded_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
