"""empty message

Revision ID: ae3ac6c2b432
Revises: 9585445c652b
Create Date: 2023-11-30 03:12:28.311670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae3ac6c2b432'
down_revision = '9585445c652b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_column('hydration_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hydration_level', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
