"""empty message

Revision ID: b87e85d17012
Revises: c29c02027fdb
Create Date: 2023-11-29 15:15:51.066071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87e85d17012'
down_revision = 'c29c02027fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach_info', schema=None) as batch_op:
        batch_op.drop_constraint('coach_info_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'members', ['member_id'], ['member_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('coach_info_ibfk_1', 'members', ['member_id'], ['member_id'])

    # ### end Alembic commands ###
