"""empty message

Revision ID: c29c02027fdb
Revises: dec7539844da
Create Date: 2023-11-29 13:37:41.247775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c29c02027fdb'
down_revision = 'dec7539844da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach_info', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('phone')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)

    with op.batch_alter_table('coach_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
