"""empty message

Revision ID: c6a9487f0e5a
Revises: 
Create Date: 2023-12-17 18:07:17.886208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6a9487f0e5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_column('sequence')

    with op.batch_alter_table('workout_plan_links', schema=None) as batch_op:
        batch_op.drop_column('sequence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence', mysql.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
