"""empty message

Revision ID: d0211748bdbc
Revises: 5c3a7483a369
Create Date: 2023-12-05 23:24:19.827649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0211748bdbc'
down_revision = '5c3a7483a369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches_members_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches_members_link', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
