"""empty message

Revision ID: d3686d1988ac
Revises: 
Create Date: 2023-11-25 20:59:27.466622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3686d1988ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Boolean(), nullable=False))
        batch_op.drop_column('is_coach')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_coach', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
