"""empty message

Revision ID: e45aa4b59393
Revises: 
Create Date: 2023-12-16 18:45:51.708770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e45aa4b59393'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatHistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatkey', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('sender', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['sender'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chathistory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chathistory',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chatkey', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('sender', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipient', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['recipient'], ['members.member_id'], name='chathistory_ibfk_2'),
    sa.ForeignKeyConstraint(['sender'], ['members.member_id'], name='chathistory_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('chatHistory')
    # ### end Alembic commands ###
