"""empty message

Revision ID: f3f9a1e3b169
Revises: b4b2e22123e5
Create Date: 2023-11-29 16:08:48.517362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3f9a1e3b169'
down_revision = 'b4b2e22123e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwords', schema=None) as batch_op:
        batch_op.drop_constraint('passwords_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'members', ['member_id'], ['member_id'], ondelete='CASCADE')
        batch_op.drop_column('password_reset_expiration')
        batch_op.drop_column('password_reset_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', mysql.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('password_reset_expiration', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('passwords_ibfk_1', 'members', ['member_id'], ['member_id'])

    # ### end Alembic commands ###
